---
stages:
  - lint
  - test

pre-commit:
  stage: lint
  image: adarnimrod/ci-images:pre-commit
  variables: &variables
    XDG_CACHE_HOME: "$CI_PROJECT_DIR/.cache"
    LANG: C.UTF-8
  script:
    - pre-commit run -a
  cache: &cache
    key: "$CI_JOB_NAME"
    paths:
      - .cache/

python2.7:
  stage: test
  image: $project:$version-slim
  allow_failure: true
  before_script: &before_script
    - pip install docutils
    - |
      if [ "$project" = "pypy" ]
      then
        apt-get update
        apt-get install -y build-essential libssl-dev
      fi
  script: &script
    - $project setup.py check -mrs
    - pip install ./
  variables: *variables
  cache: *cache
  parallel:
    matrix:
      - project: python
        version:
          - "2.7"
      - project: pypy
        version:
          - "2.7"

python3:
  stage: test
  image: $project:$version-slim
  before_script: *before_script
  script: *script
  variables: *variables
  cache: *cache
  parallel:
    matrix:
      - project: python
        version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
      - project: pypy
        version:
          - "3.6"
          - "3.7"
